pretrain: 
    id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
    md5: 9cc606b70460261de374c56548aead5b
    cached: /tmp/tranformerorc.pth

weights: https://drive.google.com/uc?id=12dTOZ9VP7ZVzwQgVvqBWz5JO5RXXW5NY

backbone: vgg19_bn
cnn:
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]          
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    hidden: 256

